version: "3"
services:
  bot:
    container_name: np3_bot
    build: 
      context: .
      dockerfile: ./deploy/Dockerfile
    restart: always
    env_file: 
      - ./deploy/.env

# docker-compose --project-directory . -f ../Docker-Services/DB/Postgres/docker-compose.yml up -d